"""Notebook/runtime dependency setup for scRareBench integration methods.

This module is deliberately stdlib-only so it can be imported immediately after
installing the scRareBench package itself with ``pip --no-deps``.  It then
installs the benchmark dependencies and the selected integration method in one
constrained transaction while preserving already-loaded scientific ABI anchors.
"""
from __future__ import annotations

from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
import os
import re
import subprocess
import sys
import tempfile
from typing import Iterable, Mapping, Sequence


DEFAULT_ANCHORS: tuple[str, ...] = (
    "numpy",
    "scipy",
    "pandas",
    "scikit-learn",
    "matplotlib",
    "h5py",
    "numba",
    "llvmlite",
    "jax",
    "jaxlib",
    "torch",
)

CORE_SMOKE_IMPORTS: tuple[str, ...] = (
    "scrarebench",
    "scrarebench.evaluation",
    "scrarebench.scib_backend",
    "scrarebench.reporting",
    "scib_metrics",
)


@dataclass(frozen=True)
class MethodRuntimeProfile:
    name: str
    requirements: tuple[str, ...]
    smoke_imports: tuple[str, ...]
    environment_defaults: Mapping[str, str]


_ACCELERATOR_ENV = {
    "XLA_PYTHON_CLIENT_PREALLOCATE": "false",
    "XLA_PYTHON_CLIENT_MEM_FRACTION": "0.60",
}

METHOD_RUNTIME_PROFILES: dict[str, MethodRuntimeProfile] = {
    "scvi": MethodRuntimeProfile(
        name="scvi",
        requirements=("scvi-tools==1.4.3",),
        smoke_imports=("scvi",),
        environment_defaults=_ACCELERATOR_ENV,
    ),
    "mrvi": MethodRuntimeProfile(
        name="mrvi",
        requirements=("scvi-tools==1.4.3",),
        smoke_imports=("scvi", "scvi.external"),
        environment_defaults=_ACCELERATOR_ENV,
    ),
    "harmony": MethodRuntimeProfile(
        name="harmony",
        requirements=("harmonypy==2.0.0",),
        smoke_imports=("harmonypy",),
        environment_defaults={},
    ),
}

_METHOD_ALIASES = {
    "scvi": "scvi",
    "scvi-tools": "scvi",
    "mrvi": "mrvi",
    "harmony": "harmony",
    "harmonypy": "harmony",
}


@dataclass(frozen=True)
class RuntimeInstallReport:
    install_target: str
    constraints_file: str
    anchors_before: dict[str, str]
    anchors_after: dict[str, str]
    changed_anchors: dict[str, tuple[str, str]]
    method_requirements: tuple[str, ...]
    smoke_imports: tuple[str, ...]
    pip_check_warnings: tuple[str, ...]
    method: str | None = None
    base_requirements: tuple[str, ...] = ()


def available_methods() -> tuple[str, ...]:
    """Return the integration-method runtime profiles shipped with scRareBench."""
    return tuple(METHOD_RUNTIME_PROFILES)


def get_method_profile(method: str) -> MethodRuntimeProfile:
    """Resolve a friendly method name/alias to its runtime profile."""
    key = str(method).strip().lower()
    canonical = _METHOD_ALIASES.get(key)
    if canonical is None:
        choices = ", ".join(available_methods())
        raise ValueError(f"Unknown method {method!r}. Available methods: {choices}")
    return METHOD_RUNTIME_PROFILES[canonical]


def _installed_version(dist_name: str) -> str | None:
    try:
        return metadata.version(dist_name)
    except metadata.PackageNotFoundError:
        return None


def _snapshot(packages: Iterable[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for name in packages:
        value = _installed_version(name)
        if value is not None:
            out[name] = value
    return out


def _write_constraints(path: Path, versions: dict[str, str]) -> None:
    path.write_text(
        "# Auto-generated by scrarebench.runtime\n"
        + "\n".join(f"{name}=={version}" for name, version in sorted(versions.items()))
        + "\n",
        encoding="utf-8",
    )


def _run(cmd: Sequence[str], *, quiet: bool) -> None:
    if not quiet:
        print("+", " ".join(cmd))
    subprocess.check_call(list(cmd))


def _base_requirements_from_installed_package() -> tuple[str, ...]:
    """Read mandatory scRareBench requirements from installed wheel/VCS metadata.

    The notebook bootstrap installs scRareBench itself with ``--no-deps`` first,
    which makes this stdlib-only module importable without importing Scanpy,
    scIB, NumPy, or any method library.  Optional extras are intentionally
    excluded here and installed through the selected method profile instead.
    """
    try:
        requirements = metadata.requires("scrarebench") or []
    except metadata.PackageNotFoundError as exc:
        raise RuntimeError(
            "scRareBench is not installed. Bootstrap it first, for example:\n"
            "  python -m pip install --no-deps "
            "git+https://github.com/amirhossein-alishahi/scRareBench_.git@main"
        ) from exc

    base = []
    for requirement in requirements:
        marker = requirement.partition(";")[2]
        if marker and re.search(r"\bextra\s*==", marker):
            continue
        base.append(requirement)
    return tuple(base)


def _fresh_process_smoke(imports: Sequence[str], *, quiet: bool) -> None:
    code = r'''
import importlib, json
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.metrics import accuracy_score
import pandas as pd

x = csr_matrix(np.eye(2, dtype=float))
assert x.shape == (2, 2)
assert accuracy_score([0, 1], [0, 1]) == 1.0
mods = {}
for name in IMPORTS:
    module = importlib.import_module(name)
    mods[name] = getattr(module, "__version__", "imported")
print(json.dumps({"ok": True, "imports": mods}, sort_keys=True))
'''
    payload = "IMPORTS = " + repr(list(imports)) + "\n" + code
    cmd = [sys.executable, "-c", payload]
    if quiet:
        subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
    else:
        _run(cmd, quiet=False)


def _owner_name(requirement: str) -> str:
    return re.split(r"[<>=!~ ;\[]", requirement, maxsplit=1)[0].strip().lower().replace("_", "-")


def install_notebook_runtime(
    project_root: str | os.PathLike[str] | None = None,
    *,
    method: str | None = None,
    method_requirements: Sequence[str] | None = None,
    method_imports: Sequence[str] | None = None,
    anchors: Sequence[str] = DEFAULT_ANCHORS,
    quiet: bool = True,
) -> RuntimeInstallReport:
    """Install a safe scRareBench notebook runtime.

    Preferred usage is ``install_notebook_runtime(method="scvi")`` after a
    ``--no-deps`` GitHub/PyPI bootstrap install of scRareBench.  ``project_root``
    and explicit method requirements remain supported for older source-checkout
    workflows.
    """
    profile = get_method_profile(method) if method is not None else None
    if method_requirements is None:
        resolved_method_requirements = profile.requirements if profile else ()
    else:
        resolved_method_requirements = tuple(method_requirements)
    if method_imports is None:
        resolved_method_imports = profile.smoke_imports if profile else ()
    else:
        resolved_method_imports = tuple(method_imports)

    if profile:
        for key, value in profile.environment_defaults.items():
            os.environ.setdefault(key, value)

    before = _snapshot(anchors)
    constraints_dir = Path(tempfile.mkdtemp(prefix="scrarebench_constraints_"))
    constraints_file = constraints_dir / "anchors.txt"
    _write_constraints(constraints_file, before)

    if project_root is None:
        base_requirements = _base_requirements_from_installed_package()
        install_target = f"installed scrarebench=={_installed_version('scrarebench') or 'unknown'}"
        targets = [*base_requirements, *resolved_method_requirements]
    else:
        root = Path(project_root).expanduser().resolve()
        pyproject = root / "pyproject.toml"
        if not pyproject.exists():
            raise FileNotFoundError(f"pyproject.toml not found under project root: {root}")
        wheels = sorted((root / "dist").glob("scrarebench-*.whl")) if (root / "dist").exists() else []
        target = wheels[-1] if wheels else root
        install_target = str(target)
        base_requirements = ()
        targets = [str(target), *resolved_method_requirements]

    cmd = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade-strategy",
        "only-if-needed",
        "--prefer-binary",
        "--constraint",
        str(constraints_file),
        *targets,
    ]
    if quiet:
        cmd.insert(4, "-q")
    _run(cmd, quiet=quiet)

    check_cmd = [sys.executable, "-m", "pip", "check"]
    proc = subprocess.run(check_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    check_lines = tuple(
        line.strip()
        for line in proc.stdout.splitlines()
        if line.strip() and "No broken requirements found" not in line
    )

    relevant_owners = {
        "scrarebench",
        *(_owner_name(x) for x in base_requirements),
        *(_owner_name(x) for x in resolved_method_requirements),
    }
    relevant_issues: list[str] = []
    unrelated_issues: list[str] = []
    for line in check_lines:
        owner = line.split()[0].lower().replace("_", "-") if line.split() else ""
        (relevant_issues if owner in relevant_owners else unrelated_issues).append(line)
    if relevant_issues:
        raise RuntimeError("Relevant dependency conflicts after installation:\n" + "\n".join(relevant_issues))
    if unrelated_issues and not quiet:
        print("pip check reported unrelated preinstalled-environment warnings; continuing:")
        for line in unrelated_issues:
            print("  -", line)

    after = _snapshot(anchors)
    changed = {
        name: (before[name], after[name])
        for name in before.keys() & after.keys()
        if before[name] != after[name]
    }
    if changed:
        details = ", ".join(f"{k}: {a} -> {b}" for k, (a, b) in changed.items())
        raise RuntimeError(
            "Scientific ABI anchor packages changed unexpectedly during installation: " + details
        )

    smoke_imports = tuple(dict.fromkeys((*CORE_SMOKE_IMPORTS, *resolved_method_imports)))
    _fresh_process_smoke(smoke_imports, quiet=quiet)

    return RuntimeInstallReport(
        install_target=install_target,
        constraints_file=str(constraints_file),
        anchors_before=before,
        anchors_after=after,
        changed_anchors=changed,
        method_requirements=tuple(resolved_method_requirements),
        smoke_imports=smoke_imports,
        pip_check_warnings=tuple(unrelated_issues),
        method=profile.name if profile else method,
        base_requirements=tuple(base_requirements),
    )


def setup_notebook(
    method: str,
    *,
    anchors: Sequence[str] = DEFAULT_ANCHORS,
    quiet: bool = True,
) -> RuntimeInstallReport:
    """User-facing notebook helper for a registered integration method."""
    return install_notebook_runtime(method=method, anchors=anchors, quiet=quiet)


def print_install_report(report: RuntimeInstallReport) -> None:
    print("scRareBench runtime installation passed.")
    if report.method:
        print("Method profile:", report.method)
    print("Install target:", report.install_target)
    print("Method requirements:", ", ".join(report.method_requirements) or "none")
    print("Preserved scientific anchors:")
    for name, version in sorted(report.anchors_after.items()):
        print(f"  - {name}=={version}")
    print("Fresh-process smoke imports:", ", ".join(report.smoke_imports))
    print("Relevant pip dependency check: OK")
    if report.pip_check_warnings:
        print(f"Unrelated preinstalled-environment pip warnings: {len(report.pip_check_warnings)}")
