"""Generic notebook/runtime dependency setup for scRareBench.

The runtime layer is deliberately method-agnostic. scRareBench owns only its
benchmark dependencies; users own the implementation and dependencies of their
integration method. ``setup_runtime`` can optionally install arbitrary user-
supplied requirements in the same constrained transaction, without knowing or
validating a method name.

"""
from __future__ import annotations

from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
import os
import re
import subprocess
import sys
import tempfile
from typing import Iterable, Mapping, Sequence


DEFAULT_ANCHORS: tuple[str, ...] = (
    "numpy", "scipy", "pandas", "scikit-learn", "matplotlib", "h5py",
    "numba", "llvmlite", "jax", "jaxlib", "torch",
)

CORE_SMOKE_IMPORTS: tuple[str, ...] = (
    "scrarebench", "scrarebench.evaluation", "scrarebench.scib_backend",
    "scrarebench.reporting", "scib_metrics",
)


@dataclass(frozen=True)
class RuntimeInstallReport:
    install_target: str
    constraints_file: str
    anchors_before: dict[str, str]
    anchors_after: dict[str, str]
    changed_anchors: dict[str, tuple[str, str]]
    extra_requirements: tuple[str, ...]
    smoke_imports: tuple[str, ...]
    pip_check_warnings: tuple[str, ...]
    base_requirements: tuple[str, ...] = ()
    user_constraint_files: tuple[str, ...] = ()
    pip_check_before: tuple[str, ...] = ()
    pip_check_after: tuple[str, ...] = ()
    new_pip_check_issues: tuple[str, ...] = ()
    relevant_dependency_packages: tuple[str, ...] = ()



def _installed_version(dist_name: str) -> str | None:
    try:
        return metadata.version(dist_name)
    except metadata.PackageNotFoundError:
        return None


def _snapshot(packages: Iterable[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for name in packages:
        value = _installed_version(name)
        if value is not None:
            out[name] = value
    return out


def _write_constraints(path: Path, versions: dict[str, str]) -> None:
    path.write_text(
        "# Auto-generated by scrarebench.runtime\n"
        + "\n".join(f"{name}=={version}" for name, version in sorted(versions.items()))
        + "\n",
        encoding="utf-8",
    )


def _run(cmd: Sequence[str], *, quiet: bool) -> None:
    if not quiet:
        print("+", " ".join(cmd))
    subprocess.check_call(list(cmd))


def _base_requirements_from_installed_package() -> tuple[str, ...]:
    """Read mandatory scRareBench requirements from installed package metadata."""
    try:
        requirements = metadata.requires("scrarebench") or []
    except metadata.PackageNotFoundError as exc:
        raise RuntimeError(
            "scRareBench is not installed. Bootstrap it first, for example:\n"
            "  python -m pip install --no-deps "
            "git+https://github.com/amirhossein-alishahi/scRareBench_.git@v0.10.4"
        ) from exc

    base: list[str] = []
    for requirement in requirements:
        marker = requirement.partition(";")[2]
        if marker and re.search(r"\bextra\s*==", marker):
            continue
        base.append(requirement)
    return tuple(base)


def _fresh_process_smoke(imports: Sequence[str], *, quiet: bool) -> None:
    code = r'''
import importlib, json
import numpy as np
from scipy.sparse import csr_matrix
from sklearn.metrics import accuracy_score
import pandas as pd
x = csr_matrix(np.eye(2, dtype=float))
assert x.shape == (2, 2)
assert accuracy_score([0, 1], [0, 1]) == 1.0
mods = {}
for name in IMPORTS:
    module = importlib.import_module(name)
    mods[name] = getattr(module, "__version__", "imported")
print(json.dumps({"ok": True, "imports": mods}, sort_keys=True))
'''
    payload = "IMPORTS = " + repr(list(imports)) + "\n" + code
    cmd = [sys.executable, "-c", payload]
    if quiet:
        subprocess.check_output(cmd, stderr=subprocess.STDOUT, text=True)
    else:
        _run(cmd, quiet=False)


def _normalize_items(value: str | Sequence[str]) -> tuple[str, ...]:
    if isinstance(value, str):
        value = (value,)
    return tuple(str(x).strip() for x in value if str(x).strip())


def _normalize_constraint_files(
    value: str | os.PathLike[str] | Sequence[str | os.PathLike[str]],
) -> tuple[str, ...]:
    if isinstance(value, (str, os.PathLike)):
        value = (value,)
    out: list[str] = []
    for item in value:
        path = Path(item).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Constraint file not found: {path}")
        out.append(str(path))
    return tuple(out)


def _pip_check_issues() -> tuple[str, ...]:
    """Return normalized ``pip check`` issue lines without treating exit 1 as fatal.

    ``pip check`` returns a non-zero status when conflicts exist. Runtime setup
    compares the before/after sets. Classification of newly introduced issues
    happens after installation so only conflicts relevant to scRareBench or the
    user-declared method dependency closure are blocking.
    """
    proc = subprocess.run(
        [sys.executable, "-m", "pip", "check"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    return tuple(
        sorted({
            line.strip()
            for line in proc.stdout.splitlines()
            if line.strip() and "No broken requirements found" not in line
        })
    )



def _canonical_dist_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", str(name).strip()).lower()


def _requirement_name(requirement: str) -> str | None:
    """Extract a distribution name from a PEP 508-ish requirement string.

    This intentionally avoids importing ``packaging`` so ``scrarebench.runtime``
    remains importable immediately after a ``--no-deps`` bootstrap install.
    """
    match = re.match(r"\s*([A-Za-z0-9][A-Za-z0-9_.-]*)", str(requirement))
    return _canonical_dist_name(match.group(1)) if match else None


def _pip_issue_owner(issue: str) -> str | None:
    match = re.match(r"\s*([A-Za-z0-9][A-Za-z0-9_.-]*)\s", str(issue))
    return _canonical_dist_name(match.group(1)) if match else None


def _distribution_roots_from_imports(imports: Sequence[str]) -> set[str]:
    roots: set[str] = set()
    try:
        mapping = metadata.packages_distributions()
    except Exception:
        return roots
    for import_name in imports:
        top_level = str(import_name).split(".", 1)[0]
        for dist_name in mapping.get(top_level, ()) or ():
            roots.add(_canonical_dist_name(dist_name))
    return roots


def _relevant_dependency_closure(
    *,
    extra_requirements: Sequence[str],
    extra_imports: Sequence[str],
) -> tuple[str, ...]:
    """Return installed distributions relevant to scRareBench + user method.

    We traverse installed requirement metadata from ``scrarebench`` and every
    user-supplied requirement/import root. Optional-extra-only requirements are
    skipped. Over-including an installed dependency is safe: it merely makes a
    real conflict blocking rather than warning-only.
    """
    roots = {_canonical_dist_name("scrarebench")}
    roots.update(
        name for name in (_requirement_name(req) for req in extra_requirements)
        if name
    )
    roots.update(_distribution_roots_from_imports(extra_imports))

    seen: set[str] = set()
    queue = list(sorted(roots))
    while queue:
        name = queue.pop()
        if name in seen:
            continue
        seen.add(name)
        try:
            dist = metadata.distribution(name)
        except metadata.PackageNotFoundError:
            continue
        except Exception:
            continue

        for requirement in dist.requires or ():
            marker = requirement.partition(";")[2]
            if marker and re.search(r"\bextra\s*==", marker):
                continue
            dep = _requirement_name(requirement)
            if not dep or dep in seen:
                continue
            try:
                metadata.distribution(dep)
            except metadata.PackageNotFoundError:
                continue
            except Exception:
                continue
            queue.append(dep)

    return tuple(sorted(seen))

def setup_runtime(
    *,
    extra_requirements: str | Sequence[str] = (),
    extra_imports: str | Sequence[str] = (),
    constraint_files: str | os.PathLike[str] | Sequence[str | os.PathLike[str]] = (),
    environment_defaults: Mapping[str, str] | None = None,
    anchors: Sequence[str] = DEFAULT_ANCHORS,
    quiet: bool = True,
    project_root: str | os.PathLike[str] | None = None,
) -> RuntimeInstallReport:
    """Install and validate a safe, method-agnostic scRareBench runtime.

    ``extra_requirements`` and ``extra_imports`` are supplied by the user for
    *their* method. scRareBench never interprets the method name or infers its
    dependencies. Existing ABI-sensitive packages are constrained to their
    already-installed versions. Optional ``constraint_files`` let a user or a
    release notebook provide an explicit reproducibility constraint set.

    Dependency health is checked both before and after installation. New
    conflicts are fatal only when their owning distribution belongs to the
    installed dependency closure of scRareBench or the user-supplied method
    requirements/imports. New conflicts belonging only to unrelated preinstalled
    environment packages are reported as warnings. This keeps real transitive
    method conflicts blocking without making unrelated Colab packages fatal.
    """
    extras = _normalize_items(extra_requirements)
    imports = _normalize_items(extra_imports)
    user_constraints = _normalize_constraint_files(constraint_files)
    for key, value in (environment_defaults or {}).items():
        os.environ.setdefault(str(key), str(value))

    pip_check_before = _pip_check_issues()
    before = _snapshot(anchors)
    constraints_dir = Path(tempfile.mkdtemp(prefix="scrarebench_constraints_"))
    constraints_file = constraints_dir / "anchors.txt"
    _write_constraints(constraints_file, before)

    if project_root is None:
        base_requirements = _base_requirements_from_installed_package()
        install_target = f"installed scrarebench=={_installed_version('scrarebench') or 'unknown'}"
        targets = [*base_requirements, *extras]
    else:
        root = Path(project_root).expanduser().resolve()
        pyproject = root / "pyproject.toml"
        if not pyproject.exists():
            raise FileNotFoundError(f"pyproject.toml not found under project root: {root}")
        wheels = sorted((root / "dist").glob("scrarebench-*.whl")) if (root / "dist").exists() else []
        target = wheels[-1] if wheels else root
        install_target = str(target)
        base_requirements = ()
        targets = [str(target), *extras]

    cmd = [
        sys.executable, "-m", "pip", "install",
        "--upgrade-strategy", "only-if-needed", "--prefer-binary",
        "--constraint", str(constraints_file),
    ]
    for user_constraint in user_constraints:
        cmd.extend(["--constraint", user_constraint])
    cmd.extend(targets)
    if quiet:
        cmd.insert(4, "-q")
    _run(cmd, quiet=quiet)

    pip_check_after = _pip_check_issues()
    before_set = set(pip_check_before)
    new_issues = tuple(issue for issue in pip_check_after if issue not in before_set)
    relevant_packages = set(
        _relevant_dependency_closure(
            extra_requirements=extras,
            extra_imports=imports,
        )
    )
    fatal_new_issues: list[str] = []
    unrelated_new_issues: list[str] = []
    for issue in new_issues:
        owner = _pip_issue_owner(issue)
        if owner is None or owner in relevant_packages:
            fatal_new_issues.append(issue)
        else:
            unrelated_new_issues.append(issue)

    if fatal_new_issues:
        raise RuntimeError(
            "Relevant dependency conflicts were introduced by runtime installation:\n"
            + "\n".join(fatal_new_issues)
        )

    preexisting_issues = tuple(issue for issue in pip_check_after if issue in before_set)
    nonblocking_issues = tuple((*preexisting_issues, *unrelated_new_issues))
    if nonblocking_issues and not quiet:
        print("pip check reported non-blocking environment warnings; continuing:")
        for line in nonblocking_issues:
            print("  -", line)

    after = _snapshot(anchors)
    changed = {
        name: (before[name], after[name])
        for name in before.keys() & after.keys()
        if before[name] != after[name]
    }
    if changed:
        details = ", ".join(f"{k}: {a} -> {b}" for k, (a, b) in changed.items())
        raise RuntimeError("Scientific ABI anchor packages changed unexpectedly during installation: " + details)

    smoke_imports = tuple(dict.fromkeys((*CORE_SMOKE_IMPORTS, *imports)))
    _fresh_process_smoke(smoke_imports, quiet=quiet)
    return RuntimeInstallReport(
        install_target=install_target,
        constraints_file=str(constraints_file),
        anchors_before=before,
        anchors_after=after,
        changed_anchors=changed,
        extra_requirements=extras,
        smoke_imports=smoke_imports,
        pip_check_warnings=nonblocking_issues,
        base_requirements=tuple(base_requirements),
        user_constraint_files=user_constraints,
        pip_check_before=pip_check_before,
        pip_check_after=pip_check_after,
        new_pip_check_issues=new_issues,
        relevant_dependency_packages=tuple(sorted(relevant_packages)),
    )


def print_install_report(report: RuntimeInstallReport) -> None:
    print("scRareBench runtime installation passed.")
    print("Install target:", report.install_target)
    print("User-supplied extra requirements:", ", ".join(report.extra_requirements) or "none")
    if report.user_constraint_files:
        print("User constraint files:", ", ".join(report.user_constraint_files))
    print("Preserved scientific anchors:")
    for name, version in sorted(report.anchors_after.items()):
        print(f"  - {name}=={version}")
    print("Fresh-process smoke imports:", ", ".join(report.smoke_imports))
    if report.new_pip_check_issues:
        print(
            "New unrelated pip conflicts reported as warnings:",
            len(report.new_pip_check_issues),
        )
    else:
        print("New pip dependency conflicts introduced: none")
    if report.pip_check_warnings:
        print(f"Non-blocking environment pip warnings: {len(report.pip_check_warnings)}")
